# Site Settings
title                    : "Wenhao Hu (胡文浩)"
description              : "3rd-year Master student at Intelligame Lab, UESTC. Research interests: Large Language Models, AI4Code, Social Media Analysis."
repository               : "HWH-2000/HWH-2000.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      :  # 可选

# SEO Related
google_site_verification :  
bing_site_verification   :  
baidu_site_verification  :  

# Site Author
author:
  name             : "Wenhao Hu (胡文浩)"
  avatar           : "images/HWH.jpg"   # 头像路径
  bio              : "Master student in Computer Science @ UESTC, research on LLMs, AI4Code, and Social Media Analysis."
  location         : "Chengdu, China"
  employer         : "Intelligame Lab, UESTC"
  googlescholar    : "https://scholar.google.com/citations?user=TIGGcswAAAAJ&hl=zh-CN"
  email            : "wenhaohu2000@gmail.com"
  github           : "HWH-2000"
  linkedin         :  # 你有 LinkedIn 可以加
  dblp             :  # https://dblp.org/pid/xxxx.html 如果有
  orcid            :  # https://orcid.org/xxxx 如果有

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 

# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
